### PR TITLE
Armstrong number program

### PR DESCRIPTION
**Pull request by Nikhil-2002**

### CODE REVIEW

**Comment by Nikhil-2002** [comment]
Sir how much time it will take for merging ?

**Comment by Nikhil-2002** [comment]
hey @RajkumarSony  review and merge please

**Comment by RajkumarSony** [comment]
Only project will be merge. Thank you.

**Comment by RajkumarSony** [comment]
If Excluded then contribute here.. https://github.com/RajkumarSony/LeetCode-Solutions.

**Pull request merged**
